name: Sehatin Frontend CI/CD

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.Js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}

    if: github.ref == 'refs/heads/main'

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Chmod private key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.GCLOUD_SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: SSH to google cloud
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{secrets.GCP_USERNAME}}@${{secrets.EXTERNAL_IP}} "
          sudo docker container rm -f sehatin_frontend || true &&
          sudo docker image rm -f ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest || true &&
          sudo docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest &&
          sudo docker run --name sehatin_frontend -d -p ${{secrets.PORT}}:${{secrets.PORT}} ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}:latest"
    if: github.ref == 'refs/heads/main'